package com.example.features.marketplace

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.domain.model.User
import com.example.domain.model.Store
import com.example.domain.model.SubscriptionRequest
import com.example.domain.repository.AuthRepository
import com.example.domain.repository.StoreRepository
import com.example.domain.usecase.SubmitSubscriptionRequestUseCase
import com.example.domain.usecase.GetSubscriptionRequestsByStoreUseCase
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import kotlinx.coroutines.Job

data class MarketplaceUiState(
    val user: User? = null,
    val userStoreId: String? = null,
    val hasStore: Boolean = false,
    val isLoading: Boolean = false,
    val ownerStore: Store? = null,
    val pendingRequests: List<SubscriptionRequest> = emptyList(),
    val subscribingTier: String? = null,
    val actionMessage: String? = null
)

class MarketplaceViewModel(
    private val authRepo: AuthRepository,
    private val storeRepo: StoreRepository,
    private val submitSubscriptionRequestUseCase: SubmitSubscriptionRequestUseCase,
    private val getSubscriptionRequestsByStoreUseCase: GetSubscriptionRequestsByStoreUseCase
) : ViewModel() {

    private val _state = MutableStateFlow(MarketplaceUiState())
    val state: StateFlow<MarketplaceUiState> = _state.asStateFlow()

    private var requestsObservationJob: Job? = null

    init {
        observeCurrentUserAndStore()
    }

    private fun observeCurrentUserAndStore() {
        viewModelScope.launch {
            _state.update { it.copy(isLoading = true) }
            authRepo.currentUser.collect { user ->
                _state.update { it.copy(user = user) }
                if (user != null) {
                    val store = storeRepo.getStoreByOwnerId(user.id)
                    _state.update { 
                        it.copy(
                            isLoading = false,
                            hasStore = store != null,
                            userStoreId = store?.id,
                            ownerStore = store
                        )
                    }
                    if (store != null) {
                        observeSubscriptionRequests(store.id)
                    } else {
                        cancelRequestsObservation()
                        _state.update { it.copy(pendingRequests = emptyList()) }
                    }
                } else {
                    cancelRequestsObservation()
                    _state.update { 
                        it.copy(
                            isLoading = false,
                            hasStore = false,
                            userStoreId = null,
                            ownerStore = null,
                            pendingRequests = emptyList()
                        )
                    }
                }
            }
        }
    }

    private fun observeSubscriptionRequests(storeId: String) {
        cancelRequestsObservation()
        requestsObservationJob = viewModelScope.launch {
            getSubscriptionRequestsByStoreUseCase(storeId).collect { result ->
                result.fold(
                    onSuccess = { requests ->
                        _state.update { it.copy(pendingRequests = requests.filter { r -> r.status == "pending" }) }
                    },
                    onFailure = { error ->
                        _state.update { it.copy(actionMessage = "Error loading requests: ${error.localizedMessage}") }
                    }
                )
            }
        }
    }

    private fun cancelRequestsObservation() {
        requestsObservationJob?.cancel()
        requestsObservationJob = null
    }

    fun requestSubscription(tier: String) {
        val currentUser = _state.value.user
        val currentStore = _state.value.ownerStore
        if (currentUser == null) {
            _state.update { it.copy(actionMessage = "Please sign in to request a plan.") }
            return
        }
        if (currentStore == null) {
            _state.update { it.copy(actionMessage = "Please create a store first to subscribe.") }
            return
        }

        // Double check if there's already a pending request for this tier:
        val alreadyPending = _state.value.pendingRequests.any { it.requestedTier == tier }
        if (alreadyPending) {
            _state.update { it.copy(actionMessage = "A request for $tier is already pending.") }
            return
        }

        viewModelScope.launch {
            _state.update { it.copy(subscribingTier = tier) }
            val request = SubscriptionRequest(
                requestId = "", // Will be generated by repository/document id
                userId = currentUser.id,
                storeId = currentStore.id,
                requestedTier = tier,
                requestDate = System.currentTimeMillis(),
                status = "pending"
            )
            submitSubscriptionRequestUseCase(request).fold(
                onSuccess = {
                    _state.update { 
                        it.copy(
                            subscribingTier = null,
                            actionMessage = "Subscription request for $tier submitted successfully!"
                        )
                    }
                },
                onFailure = { error ->
                    _state.update { 
                        it.copy(
                            subscribingTier = null,
                            actionMessage = "Failed to submit request: ${error.localizedMessage}"
                        )
                    }
                }
            )
        }
    }

    fun clearActionMessage() {
        _state.update { it.copy(actionMessage = null) }
    }

    override fun onCleared() {
        super.onCleared()
        cancelRequestsObservation()
    }
}
